name: ecg
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - autopep8
  - h5py
  - jupyterlab
  - matplotlib
  - pandas
  - pylint
  - pytorch
  - scikit-learn
  - torchaudio
  - torchvision
  - tqdm
  - wfdb
